### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by archervanderwaal** [kostaskougios/cloning#100]
Caused by: java.lang.NoClassDefFoundError: Script_1594193672548_1483/1087594064
    at sun.reflect.GeneratedSerializationConstructorAccessor176.newInstance(Unknown Source) ~[?:?]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_45]
    at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48) ~[objenesis-3.0.1.jar!/:3.0.1]
    at com.rits.cloning.Cloner$CloneObjectCloner.deepClone(Cloner.java:629) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.cloneInternal(Cloner.java:457) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:663) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.access$1300(Cloner.java:26) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner$CloneObjectCloner.deepClone(Cloner.java:635) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.cloneInternal(Cloner.java:457) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner$1.deepClone(Cloner.java:130) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.FastClonerConcurrentHashMap.clone(FastClonerConcurrentHashMap.java:18) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner$FastClonerCloner.deepClone(Cloner.java:536) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.cloneInternal(Cloner.java:457) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:663) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.access$1300(Cloner.java:26) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner$CloneObjectCloner.deepClone(Cloner.java:635) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.cloneInternal(Cloner.java:457) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:663) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.access$1300(Cloner.java:26) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner$CloneObjectCloner.deepClone(Cloner.java:635) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.cloneInternal(Cloner.java:457) ~[cloning-1.10.3.jar!/:?]
    at com.rits.cloning.Cloner.deepClone(Cloner.java:348) ~[cloning-1.10.3.jar!/:?]

**Comment by ZhenXiongQian** [comment]
Can you provide any details, like the example code
