### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by devendrant** [kostaskougios/cloning#55]
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
	at com.rits.cloning.FastClonerHashMap.clone(FastClonerHashMap.java:17)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerArrayList.clone(FastClonerArrayList.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerHashMap.clone(FastClonerHashMap.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneArray(Cloner.java:473)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:429)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerArrayList.clone(FastClonerArrayList.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneArray(Cloner.java:473)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:429)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerHashSet.clone(FastClonerHashSet.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:417)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:449)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:432)
	at com.rits.cloning.Cloner.deepClone(Cloner.java:302)
	at com.piat.rest.PiaRS.getPriorReviewRecord(PiaRS.java:665)
	at com.piat.rest.PiaRS$Proxy$_$$_WeldClientProxy.getPriorReviewRecord(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:372)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1682)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:318)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:160)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:734)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:673)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:99)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:174)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:415)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:282)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:459)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:167)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:201)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:175)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:235)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:119)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:284)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:201)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:133)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:112)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:77)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:561)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:117)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:56)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:137)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kostaskougios** [comment]
This doesn't seem to be a cloner specific issue. Are you cloning a hashmap that is concurrently accessed by other threads? Also can you please provide more information on what you are cloning, a piece of code that does it etc.
