### ISSUE TITLE
NoSuchFieldException for static fields in super class

### ISSUE THREAD

**Issue by getconcar** [kostaskougios/cloning#56]
I have classes `Parent` and `Child`.

- `Child` is a subclass of `Parent`: `Parent <-- Child`
- `Parent` has a static field `staticFieldParent`
- `Child` has a static field `staticFieldChild`

When trying to register static fields for subclass `Child`, like so: `cloner.registerStaticFields(Child.class)`, a `NoSuchFieldException` occurs saying `staticFieldParent` cannot be found:

The exception occurs in method `Cloner.registerConstant(Class<?> c, String privateFieldName)`. During debugging I noticed that the code in that method tries to find the field `staticFieldParent` in class `Child`, which fails of course.

The issue can be reproduced with these unit tests:
```
import com.rits.cloning.Cloner;
import org.junit.Test;

public class ClonerTest {
    public static class Parent {
        private String instanceFieldParent;
        private static String staticFieldParent;
    }

    public static class Child extends Parent {
        private String instanceFieldChild;
        private static String staticFieldChild;
    }

    @Test
    public void testStaticFields_Parent() {
        Cloner cloner = new Cloner();
        cloner.registerStaticFields(Parent.class);
        // Works fine
    }

    @Test
    public void testStaticFields_Child() {
        Cloner cloner = new Cloner();
        cloner.registerStaticFields(Child.class);
        // Fails
    }
}
```

Stacktrace:
```
java.lang.RuntimeException: java.lang.NoSuchFieldException: staticFieldParent
	at com.rits.cloning.Cloner.registerConstant(Cloner.java:132)
	at com.rits.cloning.Cloner.registerStaticFields(Cloner.java:185)
	at (...).ClonerTest.testStaticFields_Child(ClonerTest.java:26)
Caused by: java.lang.NoSuchFieldException: staticFieldParent
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at com.rits.cloning.Cloner.registerConstant(Cloner.java:125)
	... 24 more
```

**Comment by kostaskougios** [comment]
fixed on 1.9.4
