### ISSUE TITLE
deepClone Error

### ISSUE THREAD

**Issue by qingw** [kostaskougios/cloning#64]
I use version 1.9.6  java8 linux env:   I just clone activity's TaskDefine object: after I got this, jvm is crashed. thrift process is exit
11-30 09:03:06 ERROR AbstractNonblockingServer$FrameBuffer - Unexpected throwable while invoking!
java.lang.NoClassDefFoundError: java/lang/UNIXProcess$$Lambda$5/214585935
	at sun.reflect.GeneratedSerializationConstructorAccessor138.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:48)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at com.rits.cloning.ObjenesisInstantiationStrategy.newInstance(ObjenesisInstantiationStrategy.java:17)
	at com.rits.cloning.Cloner.newInstance(Cloner.java:276)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:441)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneArray(Cloner.java:477)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:433)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerArrayList.clone(FastClonerArrayList.java:19)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:421)
	at com.rits.cloning.Cloner$1.deepClone(Cloner.java:104)
	at com.rits.cloning.FastClonerHashMap.clone(FastClonerHashMap.java:20)
	at com.rits.cloning.Cloner.fastClone(Cloner.java:115)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:421)
	at com.rits.cloning.Cloner.cloneObject(Cloner.java:453)
	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:436)
	at com.rits.cloning.Cloner.deepClone(Cloner.java:306)

**Comment by kostaskougios** [comment]
see https://github.com/kostaskougios/cloning/issues/45

"It seems this is due to the lambda class names contain a /. i.e.
com.rits.tests.cloning.Jdk8Class2$$Lambda$1/836514715
Then the classloader replaces / with a dot and tries to load
com.rits.tests.cloning.Jdk8Class2$$Lambda$1.836514715
which is not valid. So far I didn't find a work around as the problem is not part of my code."
