### ISSUE TITLE
Using SAME_INSTANCE_INSTEAD_OF_CLONE strategy 

### ISSUE THREAD

**Issue by eladh** [kostaskougios/cloning#65]
Hi @kostaskougios 

we trying to use the SAME_INSTANCE_INSTEAD_OF_CLONE strategy and we getting the following error : 

```

java.lang.IllegalArgumentException: Can not set com.idi.framework.common.test.usecase.model.PojoTestEnum field PearlTestCloning$TestMe.testEnum to PearlTestCloning$TestMe

	atsun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
	at java.lang.reflect.Field.set(Field.java:758) 
```

the issue may occur because applyCloningStrategy return o instead of fieldObject and the Field.set trigger this error.

```
	private Object applyCloningStrategy(Map<Object, Object> clones, Object o, Object fieldObject, Field field) throws IllegalAccessException {
		for (ICloningStrategy strategy : cloningStrategies) {
			ICloningStrategy.Strategy s = strategy.strategyFor(o, field);
			if (s == ICloningStrategy.Strategy.NULL_INSTEAD_OF_CLONE) return null;
			if (s == ICloningStrategy.Strategy.SAME_INSTANCE_INSTEAD_OF_CLONE) return o;
		}
		return cloneInternal(fieldObject, clones);
	} 
```

```

// clones o, no questions asked!
	private <T> T cloneObject(T o, Map<Object, Object> clones, Class<T> clz) throws IllegalAccessException {
		final T newInstance = newInstance(clz);
		if (clones != null) {
			clones.put(o, newInstance);
		}
		final List<Field> fields = allFields(clz);
		for (final Field field : fields) {
			final int modifiers = field.getModifiers();
			if (!Modifier.isStatic(modifiers)) {
				if (!(nullTransient && Modifier.isTransient(modifiers))) {
					// request by Jonathan : transient fields can be null-ed
					final Object fieldObject = field.get(o);
					final boolean shouldClone = (cloneSynthetics || !field.isSynthetic()) && (cloneAnonymousParent || !isAnonymousParent(field));
					final Object fieldObjectClone = clones != null ? (shouldClone ? applyCloningStrategy(clones, o, fieldObject, field) : fieldObject) : fieldObject;
					

field.set(newInstance, fieldObjectClone);

					if (dumpCloned != null && fieldObjectClone != fieldObject) {
						dumpCloned.cloning(field, o.getClass());
					}
				}
			}
		}
		return newInstance;
	}


```
thanks in advance,
elad

**Comment by kostaskougios** [comment]
fixed in version 1.9.9
