### ISSUE TITLE
Stackoverflow cloning large ConcurrentLinkedQueue

### ISSUE THREAD

**Issue by bmsq** [kostaskougios/cloning#79]
The following test case triggers a Stackoverflow using v1.9.10.:
```
import java.util.Collection;
import java.util.concurrent.ConcurrentLinkedQueue;

import com.rits.cloning.Cloner;

public class CrashTest {
	private Collection<Integer> list = new ConcurrentLinkedQueue<>();

	public static void main(String[] args) {
		CrashTest test = new CrashTest();
		for (int i = 0; i < 3000; ++i) {
			test.list.add(i);
		}
		Cloner cloner = new Cloner();
		cloner.deepClone(test);
	}
}
```

> Exception in thread "main" java.lang.StackOverflowError
> 	at com.rits.cloning.Cloner.cloneObject(Cloner.java:464)
> 	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:454)
> 	at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:488)
> 	at com.rits.cloning.Cloner.cloneObject(Cloner.java:471)
> 	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:454)
> 	at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:488)
> 	at com.rits.cloning.Cloner.cloneObject(Cloner.java:471)
> 	at com.rits.cloning.Cloner.cloneInternal(Cloner.java:454)
> 	at com.rits.cloning.Cloner.applyCloningStrategy(Cloner.java:488)
> 	at com.rits.cloning.Cloner.cloneObject(Cloner.java:471)
>    .... loop continues ...

**Comment by kostaskougios** [comment]
fixed in 1.9.11
